### PR TITLE
Added command for running a ROS test file (ROS1)

### PR DESCRIPTION
**Pull request by RyanDraves**
While exploring #330, I added a command for running rostest files as part of broader support for rostest. Since it seems debugging support is already working, I decided to submit this feature independently. As I'm not familiar with ROS2, this is implemented for just ROS1.

### CODE REVIEW

**Comment by ooeygui** [comment]
Wow, thank you for your contribution!

**Review by ooeygui — APPROVED** [review]
Works as advertised! Thank you :-)

**Comment by favallone20** [comment]
Sorry, but I didn't understand how to use this new feature in the launch,json file of vscode.
Can you provide me an example? @RyanDraves @ooeygui

**Comment by ooeygui** [comment]
Could you add a github issue for improved documentation of this feature?

The way it works is using the ROS launch file, but instead of using roslaunch, it uses rostest. It works very similar to:
https://www.youtube.com/watch?v=uqqHgYsskJI&list=PL2dJBq8ig-vihvDVw-D5zAYOArTMIX0FA&index=7

**Comment by favallone20** [comment]
Yes, I will do it. Unfortunately,  I didn't understand how to do that from the video because there isn't an example for rostest.
So what should I write in the launch.json file, that you can see here https://youtu.be/uqqHgYsskJI?t=480, for debugging a ros test?

**Pull request merged**
