### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by kowyo**
Corrected a typo in the vscode-ros from "VSCode" to "VS Code" to maintain consistency with the [vscode repository](https://github.com/microsoft/vscode). This typo fix enhances readability and aligns with established conventions.

### CODE REVIEW

**Comment by kowyo** [comment]
@microsoft-github-policy-service agree

**Review by ooeygui — APPROVED** [review]
Thank you for the contribution!

**Comment by kowyo** [comment]
Thanks for the quick approval as this is my very first PR to a project that I deeply admire. May I know what additional steps I need to take to meet the archive-vsix check? I noticed that the previous pull request (#1270) which also updated the README.md has not been merged yet due to the same issue (archive-vsix). I am concerned that my pull request may face a similar fate.

Thank you in advance for your concern and advice.

**Comment by ooeygui** [comment]
@kowyo Thank you for the kind words - I appreciate the PR! 
I need to investigate the CI check - I'll look into it later today.

**Comment by ooeygui** [comment]
Since this is just a doc change, I'll push it. Thanks!

**Comment by kowyo** [comment]
Thanks for merging my PR! ❤️

**Pull request merged**
