### PR TITLE
Allow custom ROS root path to be provided

### PR DESCRIPTION
**Pull request by kunaltyagi**
TODO:
1. Change the os path seperator (How? Don't know the package used here)
2. Maybe change the instructions

### CODE REVIEW

**Comment by kunaltyagi** [comment]
`typeof(distro)` is not `"string"`?

**Comment by ooeygui** [comment]
@kunaltyagi Thanks for adding features to vscode. 
distro is read from the Extension configuration. Check out https://code.visualstudio.com/api/references/vscode-api#WorkspaceConfiguration. It needs to be turned into a string.

Can you add to this post what tests you ran before issuing the pull request?

**Comment by kunaltyagi** [comment]
I don't have ROS installed in `/opt/ros/<distro>`. Moreover the extension can't work with workspace overlays.

I tested with both, and the error notification of failing to source disappears with my PR

**Comment by ooeygui** [comment]
Sorry for the delay on this.

**Comment by kunaltyagi** [comment]
Any actionable item for me?

**Comment by ooeygui** [comment]
This fix is kind of on the older side. I've been considering how to handle custom roots - I'm not a fan of keying off sub-contents of an environment variable.
ROS1 uses the `ROS_ROOT` environment variable. 
Similarly ROS2 uses `AMENT_PREFIX_PATH`

These would be better to key off of.
I'm going to close this pull request.

**Comment by kunaltyagi** [comment]
ROS_ROOT isn't sufficient enough for workspace overlays

**Pull request closed without merging**
