### PR TITLE
Stop dropping logs all over the place...

### PR DESCRIPTION
**Pull request by ruffsl**
Related:
- https://github.com/ms-iot/vscode-ros/pull/497
- https://github.com/ms-iot/vscode-ros/issues/404

cc @ooeygui

### CODE REVIEW

**Review by ooeygui — APPROVED** [review]
Good catch - thank you for the contribution!

**Comment by ruffsl** [comment]
@ooeygui looks like all CI is passing. Could we cut a minor/patch release?

**Comment by ooeygui** [comment]
Thank you for the contribution. I could use some help testing the release. I have one big issue I'm working on related to URDF before we can push it.

**Comment by ruffsl** [comment]
> I could use some help testing the release. I have one big issue I'm working on related to URDF before we can push it.

Sure, got a link to the ticket? Didn't see any recent URDF related PRs via search.

**Comment by ooeygui** [comment]
@ruffsl Thank you! I'm working on it in [the babylon](https://github.com/polyhobbyist/babylon_ros), which is what this extension depends on. Here's the bug I'm iterating on https://github.com/ms-iot/vscode-ros/issues/1139

**Pull request merged**
